---
title: "Analyze ED Outcomes Data"
author: "Zachary del Rosario"
date: 2019-11-24
output:
  github_document
---

On November 20th, the Department of Education released data on [college student
outcomes](https://www.insidehighered.com/news/2019/11/21/federal-government-releases-earnings-data-thousands-college-programs),
for the first time disaggregated by degree program.


```{r setup}
library(tidyverse)
library(ggrepel)
library(rpnd)
```

```{r load}
file_data <- "./FieldOfStudyData1516_1617_PP.csv"

df_raw <-
  file_data %>%
  read_csv(
    col_types = cols(
      UNITID          = col_double(),
      OPEID6          = col_character(),
      INSTNM          = col_character(),
      CONTROL         = col_character(),
      MAIN            = col_double(),
      CIPCODE         = col_character(),
      CIPDESC         = col_character(),
      CREDLEV         = col_double(),
      CREDDESC        = col_character(),

      COUNT           = col_double(),
      DEBTMEDIAN      = col_double(),
      DEBTPAYMENT10YR = col_double(),
      DEBTMEAN        = col_double(),
      TITLEIVCOUNT    = col_double(),
      EARNINGSCOUNT   = col_double(),
      MD_EARN_WNE     = col_double(),
      IPEDSCOUNT1     = col_character(),
      IPEDSCOUNT2     = col_character()
    )
  )

df_data <-
  df_raw %>%
  select(
    uid               = UNITID,
    institution       = INSTNM,
    control           = CONTROL,
    major             = CIPDESC,
    level             = CREDLEV,
    degree            = CREDDESC,
    count             = COUNT,
    debt_median       = DEBTMEDIAN,
    debt_payment_10yr = DEBTPAYMENT10YR,
    debt_mean         = DEBTMEAN,
    title_iv_count    = TITLEIVCOUNT,
    earnings_count    = EARNINGSCOUNT,
    earnings_median   = MD_EARN_WNE
  ) %>%
  mutate(
    debt_annual = 12 * debt_payment_10yr,
    count = if_else(is.na(count), 0, count),
    earnings_count = if_else(is.na(earnings_count), 0, earnings_count),
    title_iv_count = if_else(is.na(title_iv_count), 0, title_iv_count)
  )
```

## Some summaries
<!-- -------------------------------------------------- -->

```{r glimpse-olin}
df_data %>%
  filter(str_detect(institution, "Olin")) %>%
  select(
    major,
    debt_median,
    title_iv_count,
    earnings_median,
    earnings_count
  ) %>%
  knitr::kable()
```

```{r glimpse-hmc}
df_data %>%
  filter(str_detect(institution, "Harvey Mudd")) %>%
  select(
    major,
    debt_median,
    title_iv_count,
    earnings_median,
    earnings_count
  ) %>%
  filter(debt_median != 0) %>%
  knitr::kable()
```

```{r glimpse-rh}
df_data %>%
  filter(str_detect(institution, "Rose-Hulman")) %>%
  select(
    major,
    debt_median,
    title_iv_count,
    earnings_median,
    earnings_count
  ) %>%
  filter(debt_median != 0) %>%
  knitr::kable()
```

## EDA
<!-- -------------------------------------------------- -->

What majors receive the most Title IV funding?

```{r eda-title-iv}
df_data %>%
  group_by(major) %>%
  summarize(
    total = sum(title_iv_count, na.rm = TRUE),
    mean = mean(title_iv_count, na.rm = TRUE)
  ) %>%
  arrange(desc(total)) %>%
  head(n = 20) %>%
  knitr::kable()
```

What majors have the greatest debt?

```{r eda-debt}
df_data %>%
  group_by(major) %>%
  summarize(
    total = sum(debt_median, na.rm = TRUE),
    median = median(debt_median, na.rm = TRUE)
  ) %>%
  arrange(desc(median)) %>%
  head(n = 20) %>%
  knitr::kable()
```

How does debt compare against earnings for different majors?

```{r earnings-v-debt, fig.width=14, fig.height=10}
df_major_summaries <-
  df_data %>%
  filter(level == 3) %>% # UG only
  group_by(major) %>%
  summarize(
    earnings_median = median(earnings_median, na.rm = TRUE),
    debt_median = median(debt_median, na.rm = TRUE)
  ) %>%
  ## Categorize earnings-debt space
  filter(!is.na(debt_median), !is.na(earnings_median)) %>%
  add_pareto(
    max(debt_median) | max(earnings_median),
    var = "expensive"
  ) %>%
  add_pareto(
    min(debt_median) | max(earnings_median),
    var = "efficient"
  ) %>%
  add_pareto(
    max(debt_median) | min(earnings_median),
    var = "poor"
  ) %>%
  mutate(plain = !expensive & !efficient & !poor) %>%
  gather(key = "type", value = "flag", expensive, efficient, poor, plain) %>%
  filter(flag) %>%
  select(-flag) %>%
  ## Aesthetics
  mutate(major = str_wrap(major, width = 15))

## Plot
df_major_summaries %>%
  filter(type != "plain") %>%
  ggplot(aes(debt_median, earnings_median)) +
  geom_point(
    data = df_major_summaries %>%
      filter(type == "plain") %>%
      select(-type),
    color = "grey80",
    size = 2
  ) +
  geom_point(
    mapping = aes(fill = type),
    color = "black",
    pch = 21,
    size = 2
  ) +
  geom_label_repel(
    mapping = aes(label = major),
    size = 3,
    force = 10
  ) +
  ## Tail
  facet_grid(type~.) +
  scale_x_log10(breaks = c(10000, 30000, 100000)) +
  scale_y_log10(breaks = c(10000, 30000, 100000)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Median Debt",
    y = "Median Earnings",
    title = "Earnings v Debt, Undergraduate Majors",
    caption = "Source: ED College Scorecard Data"
  )
```

## Engineering Major Debt and Earnings
<!-- -------------------------------------------------- -->

```{r vis-engr, fig.width=8, fig.height=12}
df_dollars <-
  df_data %>%
  filter(str_detect(major, "Engineer")) %>%
  ## Dollars
  gather(key = "type", value = "val", earnings_median, debt_annual) %>%
  group_by(major, type) %>%
  summarize(val = median(val, na.rm = TRUE)) %>%
  ungroup() %>%
  ## Factor mutation
  mutate(
    major = str_remove(major, "Engineer[[:alpha:]]+\\s?"),
    major = str_remove_all(major, "[,|\\.|-]"),
    major = str_remove(major, "\\s?$"),
    type = case_when(
      type == "debt_annual" ~ "Debt payment",
      type == "earnings_median" ~ "Earnings"
    )
  )

df_counts <-
  df_data %>%
  filter(str_detect(major, "Engineer")) %>%
  ## Dollars
  gather(key = "type", value = "count", title_iv_count, earnings_count) %>%
  mutate(count = if_else(is.na(count), 0, count)) %>%
  group_by(major, type) %>%
  summarize(count = mean(count)) %>%
  ungroup() %>%
  ## Factor mutation
  mutate(
    major = str_remove(major, "Engineer[[:alpha:]]+\\s?"),
    major = str_remove_all(major, "[,|\\.|-]"),
    major = str_remove(major, "\\s?$"),
    type = case_when(
      type == "title_iv_count" ~ "Debt payment",
      type == "earnings_count" ~ "Earnings"
    )
  )

left_join(
  df_dollars,
  df_counts,
  by = c("major", "type")
) %>%
  filter(!is.na(val)) %>%

  ggplot(aes(fct_reorder(major, val), val)) +
  geom_point(
    aes(size = count, fill = type),
    color = "black",
    pch = 21
  ) +
  scale_y_log10(breaks = c(2000, 4000, 40000, 80000)) +
  scale_fill_discrete(name = "") +
  scale_size_continuous(name = "Mean Count") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Engineering Undergraduate Major",
    y = "Annual",
    title = "Annual Graduate Debt Payment / Earnings",
    caption = "Source: ED College Scorecard Data"
  )
```

```{r vis-engr-major}
left_join(
  df_dollars,
  df_counts,
  by = c("major", "type")
) %>%
  filter(
    !is.na(val),
    count >= 10
  ) %>%

  ggplot(aes(fct_reorder(major, val), val)) +
  geom_point(
    aes(fill = type),
    color = "black",
    pch = 21,
    size = 4
  ) +
  scale_y_log10(breaks = c(3000, 4000, 40000, 80000)) +
  scale_fill_discrete(name = "") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Engineering Undergraduate Major",
    y = "Annual",
    caption = "Source: ED College Scorecard Data; mean count at least 10",
    title = "Annual Debt Payment / Earnings"
  )
```
