---
title: "Australia Fires"
author: "Zach"
date: 2019-01-11
output:
  github_document
---

Tuesday's exercise is investigating the Australia fires.

```{r}
## For Docker image
install.packages("gam")

```


```{r}
library(tidyverse)
library(sf)
library(lubridate)
library(gam)
library(modelr)

# Get the Data

df_rainfall <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')
df_temperature <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')

# IF YOU USE THIS DATA PLEASE BE CAUTIOUS WITH INTERPRETATION
df_nasa_fire <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/MODIS_C6_Australia_and_New_Zealand_7d.csv')

# For JSON File of fires
url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

df_aus_fires <- sf::st_read(url)
```

Download and unpack Australia boundary data.

```{r}
url_aus_geo <- "http://data.daff.gov.au/data/warehouse/nsaasr9nnd_022/nsaasr9nnd_02211a04es_geo___.zip"
curl::curl_download(url_aus_geo, destfile = "../data/aus.shp.zip")
unzip("../data/aus.shp.zip", exdir = "../data")
```

Load boundary data.

```{r}
df_boundaries <- sf::read_sf("../data", "aust_cd66states")
```

Process the descriptions for `control` information.

```{r}
df_aus_control <- 
  df_aus_fires %>% 
  mutate(
    control = str_extract(description, "STATUS: [\\w|\\s]+") %>% 
      str_remove(., "STATUS: ") %>% 
      str_trim(.) %>% 
      as_factor(),
    pubDate = dmy_hms(pubDate)
  )

df_aus_control %>% glimpse
```

```{r}
df_aus_control %>% pull(control) %>% unique
```



## Visualize
<!-- ----------------------------------------------------------------- -->

What is the temperature history for Australia?

```{r}
df_temperature %>% glimpse
```


```{r}
df_temperature %>% 
  mutate(date = ymd(date)) %>% 
  filter(date > ymd("2018-01-01")) %>%

  ggplot(aes(date, temperature, color = fct_reorder2(site_name, date, temperature))) +
  geom_point(size = 0.5) +
  geom_smooth(se = FALSE, size = 1)
```

```{r}
df_rainfall %>% glimpse
```


Geographic distribution of fires.

```{r}
fires_crs <- st_crs(df_aus_fires)

ggplot() +
  geom_sf(
    data = df_boundaries %>%
      st_set_crs(fires_crs)
  ) +
  geom_sf(
    data = df_aus_control,
    mapping = aes(fill = control, color = control)
  ) +
  ## Tail
  scale_fill_discrete(name = "Fire control status") +
  coord_sf(
    xlim = c(+140, +155),
    ylim = c(-40, -25)
  ) +
  guides(color = FALSE) +
  theme(legend.position = "right")
```

Timeseries

```{r}
df_aus_control %>% 
  ggplot(aes(pubDate)) +
  geom_histogram() 
```

